// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sim.Data.Context;

#nullable disable

namespace Sim.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240926001907_add-calendar")]
    partial class addcalendar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);                        

            modelBuilder.Entity("Sim.Domain.Evento.Model.EReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Local")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Owner")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Visivel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reminders", (string)null);
                });
            
#pragma warning restore 612, 618
        }
    }
}
